# Generated by Django 3.1.3 on 2020-12-29 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=40)),
                ('city', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=100)),
                ('zip', models.CharField(max_length=10)),
                ('disc', models.CharField(max_length=200)),
                ('date', models.DateField()),
            ],
        ),
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
