# Generated by Django 3.1.3 on 2020-12-29 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0002_auto_20201229_1829'),
    ]

    operations = [
        migrations.CreateModel(
            name='Personal_Contact_Form',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('phone_no', models.CharField(max_length=20)),
            ],
        ),
    ]
