# Generated by Django 3.1.3 on 2020-12-31 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0003_personal_contact_form'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact1',
        ),
        migrations.DeleteModel(
            name='Personal_Contact_Form',
        ),
    ]
